### PR TITLE
fix: publishing events with data

### PR DESCRIPTION
**Pull request by AnthonyGilliam**
In response to issue #28 https://github.com/aurelia/event-aggregator/issues

### CODE REVIEW

**Comment by AnthonyGilliam** [comment]
Refer to the repo I'm using to learn Aurelia with: https://github.com/AnthonyGilliam/Aurelia-Fundamentals for a use case example.  I'm using the BackgroundNotification object to publish and subscribe to events.

**Comment by AnthonyGilliam** [comment]
I had to convert the index.js file to AMD in order for me to bundle it properly so it could be production ready.  Here's the command I used:
`babel --presets=stage-1,es2015 --plugins=syntax-flow,transform-decorators-legacy,transform-es2015-modules-amd jspm_packages/npm/aurelia-event-aggregator@1.0.1/aurelia-event-aggregator.js > aurelia-event-aggregator.js`
Bable couldn't parse the interface and default parameters though. The preset `es2015-loose` doesn't exist anymore either. Are there any other options that I need to transpile it properly?

**Comment by EisenbergEffect** [comment]
@AnthonyGilliam Can you add a unit test for this scenario?

**Comment by StrahilKazlachev** [comment]
This does break the tests. Also as I see it, it breaks the following scenario:
```js
// Currently you can use a `class` for topic when subscribing.
events.subscribe(MyEvent, cb);
// ...
//  Your callback will get called when an instance of that `class` is published.
events.publish(new MyEvent());
```

**Comment by EisenbergEffect** [comment]
The one of the two primary use cases: subscribing on string channels and subscribing to message *types*. Going to close this since it causes a major regression. Also, we don't want to enable subscribing to object instances.

**Pull request closed without merging**
