### PR TITLE
fix(index): handle errors per callback invocation

### PR DESCRIPTION
**Pull request by StrahilKazlachev**

### CODE REVIEW

**Comment by StrahilKazlachev** [comment]
@EisenbergEffect What is the intention for invoking the callbacks in revers order? I would expect them to be invoked in order of subscription. Or is the order an implementation detail that should not be taken into consideration?

**Comment by EisenbergEffect** [comment]
It's an implementation detail. That loop is more performant than other variations.

**Comment by CasiOo** [comment]
To be honest I wouldn't even want any error handling since the event-aggregator doesn't know how to handle them.

Also, a try catch for each iteration might have a negative effect on performance?

**Comment by StrahilKazlachev** [comment]
But that means if one handler throws, all other will be skipped.

**Comment by EisenbergEffect** [comment]
Yes, a try/catch per invocation would definitely slow it down.

**Comment by StrahilKazlachev** [comment]
@EisenbergEffect So the test wasn't to ensure all handlers are run regardless of errors in some of them?

**Comment by EisenbergEffect** [comment]
No, but we should probably fix that somehow. It's not great the way it is today.

**Comment by StrahilKazlachev** [comment]
About the performance issue, is this about the V8 not optimizing function with try/catch in them? Or something else.

**Comment by EisenbergEffect** [comment]
That's the main issue if I recall. There may be a way to work around that or improve it.

**Comment by StrahilKazlachev** [comment]
@EisenbergEffect If it's that we can invoke the handler in separate function. I'll push a change shortly.

**Comment by EisenbergEffect** [comment]
That sounds good.

**Comment by StrahilKazlachev** [comment]
@EisenbergEffect I used 2 functions to skip an `if`.

**Pull request merged**
